#!/bin/bash

usage() 
{ 
	echo "Usage: $0 [-s <service id>] ]-r <recipient1,recipient2,..>] [-m <message>]" 1>&2; 
	exit 1; 
}

while getopts ":r:m:s:" o; do
	case "${o}" in
	s)
		SERVICE_ID=${OPTARG}
		;;
	r)
		 RECIPIENT_LIST=${OPTARG}
		;;
        m)
		MESSAGE=${OPTARG}
		;;
	*)
		usage
		;;
	esac
done

shift $((OPTIND-1))

if [ -z "${SERVICE_ID}" ] || [ -z "${RECIPIENT_LIST}" ] || [ -z "${MESSAGE}" ]; then
	usage
fi

/usr/bin/osascript <<-EOF

on run argv
	set RecipientList to {"$RECIPIENT_LIST"}
    	set ServiceID to "e:$SERVICE_ID"
	set Message to "$MESSAGE"
    	repeat with Recipient in RecipientList
		tell application "Messages"
			send Message to buddy Recipient of service ServiceID
		end tell
	end repeat
end run

EOF
